name: Generate ASCII Artwork

on: push

jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        -   name: Install cowsay Program
            run: sudo apt-get install cowsay -y
        -   name: execute cowsay CMD
            run: cowsay -f dragon "Run for cover, I am DRAGON Worrier" >> dragon.txt
        -   name: Upload test fiel
            uses: actions/upload-artifact@v4
            with:
                name: dragon-text-file
                path: dragon.txt
    build_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        -   name: Upload test file
            uses: actions/download-artifact@v4
            with:
                name: dragon-text-file
        -   name: Test file exists
            run: grep -i "dragon" dragon.txt 
    build_job_3:
        needs: build_job_2
        runs-on: ubuntu-latest
        steps:
        -   name: Upload test file
            uses: actions/download-artifact@v4
            with:
                name: dragon-text-file
        -   name: read file
            run: cat dragon.txt